import Navbar from "../components/navbar"
import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Navbar />
          <div className="content">{children}</div>
        </div>
        
      </body>
    </html>
  )
}
